services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: foss_directory
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    container_name: backend
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
    depends_on:
      - backend
    networks:
      - frontend

  nginx:
    image: nginx:1.27
    container_name: nginx
    attach: false
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - frontend

volumes:
  postgres-data:

networks:
  backend:
  frontend:
