services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: foss_directory
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    image: maxkemzi/foss-directory-server:latest
    container_name: backend
    restart: always
    env_file: "./server/.env"
    depends_on:
      - postgres
    networks:
      - frontend
      - backend

  frontend:
    image: maxkemzi/foss-directory-client:latest
    container_name: frontend
    restart: always
    env_file: "./client/.env"
    depends_on:
      - backend
    networks:
      - frontend

  nginx:
    image: nginx:1.27
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - frontend

volumes:
  postgres-data:

networks:
  frontend:
  backend:
