services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: foss_directory
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./server
    container_name: backend
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
