TRUNCATE refresh_tokens RESTART IDENTITY CASCADE;
TRUNCATE github_connections RESTART IDENTITY CASCADE;
TRUNCATE users RESTART IDENTITY CASCADE;
TRUNCATE projects RESTART IDENTITY CASCADE;
TRUNCATE tags RESTART IDENTITY CASCADE;
TRUNCATE roles RESTART IDENTITY CASCADE;
