TRUNCATE refresh_token RESTART IDENTITY CASCADE;
TRUNCATE github_connection RESTART IDENTITY CASCADE;
TRUNCATE user RESTART IDENTITY CASCADE;
TRUNCATE project RESTART IDENTITY CASCADE;
TRUNCATE tag RESTART IDENTITY CASCADE;
TRUNCATE role RESTART IDENTITY CASCADE;
