type ApiErrorKey =
	| "BAD_REQUEST"
	| "UNAUTHORIZED"
	| "INTERNAL_SERVER"
	| "TOO_MANY_REQUESTS"
	| "FORBIDDEN"
	| "AUTH_MISSING_HEADER"
	| "AUTH_INVALID_HEADER"
	| "AUTH_EXISTING_EMAIL"
	| "AUTH_NON_EXISTING_EMAIL"
	| "AUTH_EXISTING_USERNAME"
	| "AUTH_WRONG_PASSWORD"
	| "AUTH_INVALID_TOKEN"
	| "GITHUB_ALREADY_CONNECTED"
	| "GITHUB_CONNECTION_REQUIRED"
	| "GITHUB_EXCEEDED_RATE_LIMIT"
	| "GITHUB_EXPIRED_TOKEN"
	| "GITHUB_UNVERIFIED_EMAIL"
	| "GITHUB_INVALID_CSRF_TOKEN"
	| "PROJECT_NOT_FOUND"
	| "PROJECT_OWNER_PERMISSION_REQUIRED"
	| "PROJECT_MEMBER_PERMISSION_REQUIRED"
	| "PROJECT_REQUEST_NOT_FOUND"
	| "PROJECT_REQUEST_RECEIVER_PERMISSION_REQUIRED"
	| "PROJECT_REQUEST_ALREADY_MEMBER"
	| "USER_NOT_FOUND";

interface ApiErrorInfoType {
	message: string;
	code: string;
}

export type {ApiErrorKey, ApiErrorInfoType};
