import {GlobalModal} from "#src/components";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {FC, PropsWithChildren} from "react";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const RootLayout: FC<PropsWithChildren> = ({children}) => (
	<html lang="en" className="dark">
		<body className={inter.className}>
			<Providers>
				<div className="flex flex-col min-h-screen">{children}</div>
				<GlobalModal />
			</Providers>
		</body>
	</html>
);

export default RootLayout;
