import {GlobalModal} from "#src/components/modals";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {FC, PropsWithChildren, Suspense} from "react";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const RootLayout: FC<PropsWithChildren> = async ({children}) => {
	return (
		<html lang="en" className="dark">
			<body className={inter.className}>
				<Providers>
					<div className="flex flex-col min-h-screen">{children}</div>
					<Suspense>
						<GlobalModal />
					</Suspense>
				</Providers>
			</body>
		</html>
	);
};

export default RootLayout;
