import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import {FC, PropsWithChildren} from "react";
import {Header} from "./(header)";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const RootLayout: FC<PropsWithChildren> = ({children}) => {
	return (
		<html lang="en" className="dark">
			<body className={inter.className}>
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	);
};

export default RootLayout;
